{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "Xalendar Official API docs"
    },
    "host": "165.22.72.61",
    "tags": [
        {
            "name": "User"
        }
    ],
    "definitions": {
        "User": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "number"
                },
                "type": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                }
            }
        },
        "Event": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "number"
                },
                "name": {
                    "type": "string",
                    "description": "Lesson name"
                },
                "color": {
                    "type": "string"
                },
                "aud": {
                    "type": "string",
                    "description": "Audition for the lesson"
                },
                "link": {
                    "type": "string"
                },
                "teacher": {
                    "type": "string",
                    "description": "Teacher short full name"
                },
                "theme": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "module_id": {
                    "type": "number",
                    "description": "Id of the module to which the event belongs"
                }
            }
        },
        "Module": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "array"
                }
            }
        }
    },
    "paths": {
        "/modules": {
            "get": {
                "parameters": [
                    {
                        "name": "userId",
                        "in": "query",
                        "required": true,
                        "description": "Id of the user (example: 269788)",
                        "type": "string"
                    }
                ],
                "tags": ["Module"],
                "summary": "Get all modules for specified user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "example": []
                        }
                    }
                }
            }
        },
        "/module": {
            "post": {
                "tags": ["Module"],
                "summary": "Create module for events",
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "description": "Post json",
                        "schema": {
                            "example": {
                                "name": "Великие книги",
                                "userId": ["256720"]
                            }
                        }
                    }
                ],
                "produces": ["application/json"],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "example": {
                                "id": 5
                            }
                        }
                    }
                }
            }
        },
        "/module/{id}/event": {
            "post": {
                "tags": ["Module"],
                "summary": "Create event for specified module",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "description": "Id of the module",
                        "required": true,
                        "type": "number"
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "description": "Post json",
                        "schema": {
                            "example": {
                                "name": "Практика IT",
                                "color": "#232323",
                                "aud": "Онлайн",
                                "link": "www.discord.com",
                                "teacher": "Воробьев А.И.",
                                "theme": "Работа с Vue.js",
                                "startTime": "2021-06-05T08:30:00.000Z",
                                "endTime": "2021-06-05T10:15:00.000Z"
                            }
                        }
                    }
                ],
                "produces": ["application/json"],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "example": {
                                "id": 5
                            }
                        }
                    }
                }
            }
        },
        "/user/{userId}": {
            "get": {
                "parameters": [
                    {
                        "name": "userId",
                        "in": "path",
                        "required": true,
                        "description": "Id of the user",
                        "type": "string"
                    }
                ],
                "tags": ["User"],
                "summary": "Get specified user.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "example": {}
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "tags": ["Event"],
                "summary": "Get all events in the specified range",
                "parameters": [
                    {
                        "name": "userId",
                        "in": "query",
                        "required": true,
                        "description": "If of the user (example: 269788)",
                        "type": "string"
                    },
                    {
                        "name": "startDate",
                        "in": "query",
                        "required": true,
                        "description": "Start date (example: 2021-06-03)",
                        "type": "string"
                    },
                    {
                        "name": "endDate",
                        "in": "query",
                        "required": true,
                        "description": "End date (example: 2021-06-05)",
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "example": [
                                {
                                    "name": "Бег",
                                    "color": "#232323",
                                    "aud": "Манеж",
                                    "link": "",
                                    "theme": "Бег",
                                    "teacher": "Минеев А.А",
                                    "start_date": "2021-06-04T05:30:00.000Z",
                                    "end_date": "2021-06-04T07:15:00.000Z",
                                    "id": 18,
                                    "module_id": 5
                                },
                                {
                                    "name": "Встреча ИТС",
                                    "color": "#232323",
                                    "aud": "8-623",
                                    "link": "",
                                    "theme": "ИТС",
                                    "teacher": "Зарьянов В.в",
                                    "start_date": "2021-06-04T13:00:00.000Z",
                                    "end_date": "2021-06-04T14:35:00.000Z",
                                    "id": 25,
                                    "module_id": 5
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/event/{id}": {
            "patch": {
                "tags": ["Event"],
                "summary": "Update specified event",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "description": "Id of the users",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "in": "body",
                        "name": "body",
                        "description": "Updated json",
                        "schema": {
                            "example": {
                                "name": "Практика IT",
                                "color": "#696969",
                                "aud": "Онлайн",
                                "link": "www.discord.com",
                                "theme": "Работа с Angular.js",
                                "startTime": "2021-05-28T8:30:00.000Z",
                                "endTime": "2021-05-28T10:15:00.000Z"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "example": {
                                "id": 1,
                                "name": "Практика IT",
                                "color": "#696969",
                                "aud": "Онлайн",
                                "link": "www.discord.com",
                                "teacher": "Воробьев А.И.",
                                "theme": "Работа с Angular.js",
                                "start_time": "2021-05-29 14:15:00",
                                "end_time": "2021-05-29 15:50:00",
                                "module_id": 1
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": ["Event"],
                "summary": "Delete specified event from the system.",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "description": "Event id",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content",
                        "schema": {
                            "example": {}
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/module/{id}": {
            "delete": {
                "tags": ["Module"],
                "summary": "Delete specified event",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "description": "Id of the module",
                        "type": "number"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content",
                        "schema": {
                            "example": {}
                        }
                    },
                    "404": {
                        "description": "Not found"
                    }
                }
            }
        },
        "/module/{id}/users": {
            "patch": {
                "tags": ["Module"],
                "summary": "Add user to module",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "description": "Id of the module",
                        "type": "number"
                    },
                    {
                        "in": "body",
                        "name": "JSON data",
                        "description": "Updated json",
                        "schema": {
                            "example": {
                                "userId": "256720"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "example": {
                                "id": 1,
                                "name": "Мел",
                                "userId": ["269788", "256720"]
                            }
                        }
                    }
                }
            }
        }
    }
}
