{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Xalendar Official API docs"
  },
  "host": "xalendar.herokuapp.com",
  "tags": [
    {
      "name": "User"
    }
  ],

  "definitions": {
    "User": {
      "type": "object",
      "properties": {
        "user_id": {
          "type": "number"
        },

        "type": {
          "type": "string"
        },

        "full_name": {
          "type": "string"
        }
      }
    },

    "Event": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },

        "color": {
          "type": "string"
        },

        "aud": {
          "type": "string"
        },

        "link": {
          "type": "string"
        },

        "teacher": {
          "type": "string"
        },

        "module_name": {
          "type": "string"
        },

        "theme": {
          "type": "string"
        },

        "start_time": {
          "type": "string"
        },

        "end_time": {
          "type": "string"
        },

        "date": {
          "type": "string"
        },

        "id": {
          "type": "number"
        },

        "meeting_id": {
          "type": "number"
        },

        "user_id": {
          "type": "array"
        }
      }
    },

    "Meeting": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },

        "start_time": {
          "type": "string"
        },

        "end_time": {
          "type": "string"
        }
      }
    }
  },

  "paths": {
    "/meetings": {
      "get": {
        "parameters": [
          {
            "name": "userId",
            "in": "query",
            "required": true,
            "description": "269788",
            "type": "string"
          }
        ],
        "tags": ["Meetings"],
        "summary": "Get all meetings for specified user",

        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": [
                {
                  "name": "Практика IT",
                  "start_time": "14:15:00",
                  "end_time": "15:50:00"
                },
                {
                  "name": "Практика IT",
                  "start_time": "14:15:00",
                  "end_time": "15:50:00"
                },
                {
                  "name": "Практика IT",
                  "start_time": "14:15:00",
                  "end_time": "15:50:00"
                }
              ]
            }
          },
          "400": {
            "description": "Uncorrect userId",
            "schema": {
              "example": {
                "message": "Couldn't find meetings",
                "type": "400"
              }
            }
          }
        }
      }
    },

    "/user": {
      "get": {
        "parameters": [
          {
            "name": "fullName",
            "in": "query",
            "required": true,
            "description": "Full name of user.",
            "type": "string"
          }
        ],
        "tags": ["User"],

        "summary": "Get all events from the specified range",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },

          "400": {
            "description": "Bad get info",
            "schema": {
              "example": {
                "message": "Not found",
                "type": "400"
              }
            }
          }
        }
      }
    },

    "/events": {
      "get": {
        "tags": ["Event"],
        "summary": "Get all events in the specified range",

        "parameters": [
          {
            "name": "userId",
            "in": "query",
            "required": true,
            "description": "269788",
            "type": "string"
          },

          {
            "name": "startDate",
            "in": "query",
            "required": true,
            "description": "2021-05-20",
            "type": "string"
          },

          {
            "name": "endDate",
            "in": "query",
            "required": false,
            "description": "2021-05-31",
            "type": "string"
          }
        ],

        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": [
                {
                  "name": "Лекция IT",
                  "id": 1,
                  "color": "#696969",
                  "aud": "Онлайн",
                  "link": "www.discord.com",
                  "teacher": "Воробьев А.И.",
                  "module_name": "Мел",
                  "theme": "Введение в git",
                  "start_time": "12:00:00",
                  "end_time": "13:35:00",
                  "date": "2021-05-28",
                  "user_id": ["269788"],
                  "meeting_id": 1
                },
                {
                  "name": "Практика IT",
                  "id": 5,
                  "color": "#232323",
                  "aud": "Онлайн",
                  "link": "www.discord.com",
                  "teacher": "Воробьев А.И.",
                  "module_name": "Мел",
                  "theme": "Работа с State, Redux",
                  "start_time": "14:15:00",
                  "end_time": "15:50:00",
                  "date": "2021-05-28",
                  "user_id": ["269788", "256720"],
                  "meeting_id": 4
                }
              ]
            }
          }
        }
      }
    },
    "/event": {
      "patch": {
        "tags": ["Event"],
        "summary": "Update specified event",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Updated json",
            "schema": {
              "example": {
                "id": 5,
                "name": "Практика IT",
                "color": "#232323",
                "aud": "Онлайн",
                "link": "www.discord.com",
                "teacher": "Воробьев А.И.",
                "moduleName": "Мел",
                "theme": "Работа с State, Redux",
                "startTime": "14:15:00",
                "endTime": "15:50:00",
                "date": "2021-05-28",
                "userId": ["269788", "256720"]
              }
            }
          }
        ],

        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": {
                "id": 5
              }
            }
          }
        }
      },

      "delete": {
        "tags": ["Event"],
        "summary": "Delete event from the system.",
        "parameters": [
          {
            "in": "query",
            "name": "id",
            "description": "Event id",
            "required": true,
            "type": "string"
          }
        ],

        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": {
                "responce": 1
              }
            }
          }
        }
      },

      "post": {
        "tags": ["Event"],
        "summary": "Post event to the system.",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Post json",
            "schema": {
              "example": {
                "name": "Практика IT",
                "color": "#232323",
                "aud": "Онлайн",
                "link": "www.discord.com",
                "teacher": "Воробьев А.И.",
                "moduleName": "Мел",
                "theme": "Работа с State, Redux",
                "startTime": "14:15:00",
                "endTime": "15:50:00",
                "date": "2021-05-28",
                "userId": ["269788", "256720"]
              }
            }
          }
        ],

        "produces": ["application/json"],

        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": {
                "id": 5,
                "name": "Практика IT",
                "color": "#232323",
                "aud": "Онлайн",
                "link": "www.discord.com",
                "teacher": "Воробьев А.И.",
                "moduleName": "Мел",
                "theme": "Работа с State, Redux",
                "startTime": "14:15:00",
                "endTime": "15:50:00",
                "date": "2021-05-28",
                "userId": ["269788", "256720"],
                "meeting_id": "5"
              }
            }
          },

          "400": {
            "description": "Failed. Bad post data"
          }
        }
      }
    }
  }
}
